### ISSUE TITLE
<MAP> is taken

### ISSUE THREAD

**Issue by dret** [Maps4HTML/HTML-Map-Element#9]
seeing the discussion on https://discourse.wicg.io/t/use-cases-and-requirements-for-standardizing-web-maps/1161/5, here are some comments:

* <MAP> is taken. http://www.w3.org/TR/html4/struct/objects.html#h-13.6.1 and http://www.w3.org/TR/html5/embedded-content-0.html#the-map-element define a <MAP> element.

* <MAP> is simply intended as a map of clickable areas on an <IMG>, allowing client-side image maps. it has no relation to the "(geographic) map" concept targeted by this spec (which is about dynamically serving tiled map imagery, afaict).

my suggestion would be to cleanly separate these two things, because there is little overlap. <MAP> has been around for ages and has very different semantics.
whatever the names and markup design will end up being, it seems to me that what this initiative is trying is quite different from "HTML image maps", and it might help to separate those issues.

**Comment by prushforth** [comment]
Thanks for your suggestion.  This issue is [recorded here](https://github.com/Maps4HTML/HTML-Map-Element/issues/8).  It is a bit premature, but I agree it will be essential to smoothly integrate into the HTML vocabulary and it would be nice to eventually have the concept "marketed" independently.  I personally liked the suggestion for "webmap", but I imagine that the HTML implementors and their marketing departments will have the final word.

**Comment by dret** [comment]
sorry, should have checked the open issues first! my main concern was not so much the name itself, but to not mix it up with "image maps", which are something else entirely. i'll close this one, then.
